---
title: "bear cam sighting matrix"
author: "Ainsley"
date: "7/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Creating a dataset for the matrix of sightings by week

```{r}
library(dplyr)
library(tidyr)

cam_mat <- read.csv("C:/Users/axmac/Desktop/git-general-home/BBearOccuModels2021/bear camera by week matrix.csv")

#abbreviate the headers
ccmat <- cam_mat
colnames(ccmat)[2:11] <- stringr::str_replace(colnames(cam_mat)[2:11], "Week.", "wk") %>%
  stringr::str_sub(1, 3)
#clean up data frame
ccmat <- ccmat[-28,] %>% select(SITE_ID = Site, everything(), - X)

#make site covariate matrix/dataframe
site_covs <- read.csv("C:/Users/axmac/Desktop/Bear Kristensen Lab/arcgis_maps/2019_Sampling_Design/all_site_covariates_250m_buffercsv.csv")

#combine datasites but only take those with cameras
sitecov_cams <- left_join(ccmat, site_covs, by = "SITE_ID")
```

Now there exists a data set with the sighting's matrix as well as each camera site's covariates (all of them that exist lol)











Lets actually try a function to do renaming for us: or a loop better?
```{r}
abrv <- function(){}


colnames(cam_mat)[2:11] <- stringr::str_replace(colnames(cam_mat)[2:11], "Week.", "wk") %>%
  stringr::str_sub(1, 3)



```








