---
title: "unmarked trial 1"
author: "Ainsley"
date: "6/14/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(unmarked)
library(xlsx)
library("readxl")
library(tidyr)
library(dplyr)
```

```{r}
data <- read_excel("C:\\Users\\axmac\\Downloads\\Practice GC unmarked.xlsx")
data1 <- data %>% mutate_if(is.numeric , replace_na, replace = 0)

# y <- 
# siteCovs <- 
# obsCovs <- list( date = ...., ivel = ....)

dframe <- unmarkedFrameOccu(y = data1[,2:3], siteCovs = , obsCovs = )
```



https://doi90.github.io/lodestar/fitting-occupancy-models-with-unmarked.html 

```{r, example set up}
R <- 4 # number of sites
J <- 3 # number of visits
y <- matrix(c(
   1,1,0,
   0,0,0,
   1,1,1,
   1,0,1), nrow=R, ncol=J, byrow=TRUE)
y

site.covs <- data.frame(x1=1:4, x2=factor(c('A','B','A','B')))
site.covs

obs.covs <- list(
   x3 = matrix(c(
      -1,0,1,
      -2,0,0,
      -3,1,0,
      0,0,0), nrow=R, ncol=J, byrow=TRUE),
   x4 = matrix(c(
      'a','b','c',
      'd','b','a',
      'a','a','c',
      'a','b','a'), nrow=R, ncol=J, byrow=TRUE))
obs.covs
```

```{r, example execution}
umf <- unmarkedFrameOccu(y=y, siteCovs=site.covs, 
    obsCovs=obs.covs)   # organize data
umf                     # look at data
summary(umf)            # summarize      
fm <- occu(~1 ~1, umf)  # fit a model
fm
```

